---

- name: reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: restart kafka services
  become: yes
  service:
    name: "kafka_broker_{{item}}@{{item}}.service"
    state: "{{systemd_service_action}}"
    enabled: yes
    state: restarted
  with_sequence: start={{no_broker_start_index}} end={{no_broker_end_index}}

#  notify: reload systemd    
#- name: start kafka
#  become: yes
#  service:
#    name: kafka
#    state: started
#
#- name: stop kafka
#  become: yes
#  service:
#    name: kafka
#    state: stopped
#
#- name: restart kafka
#  become: yes
#  service:
#    name: kafka
#    state: restarted

  