version: "3.9"

networks:
  training:
    external: false

services:
#   mongo:
#       image: mongo
#       env_file: .env
#       environment:
#           - MONGO_INITDB1_DATABASE=sravz
#           - MONGO_INITDB1_USERNAME=sravz
#           - MONGO_INITDB1_PASSWORD=sravz
#           - MONGO_INITDB2_DATABASE=sravz_historical
#           - MONGO_INITDB2_USERNAME=sravz_historical
#           - MONGO_INITDB2_PASSWORD=sravz_historical
#       ports:
#         - 27017:27017
#       volumes:
#         - ./docker_volume/mongo_data:/data/db
#         - ./docker_volume/mongo_dump:/var/mongo_dump
#         - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
#       networks:
#         - training
#       labels:
#         - traefik.enable=false

#   mongo-express:
#       image: mongo-express
#       env_file: .env
#       environment:
#           - ME_CONFIG_MONGODB_SERVER=mongo
#           - ME_CONFIG_MONGODB_PORT=27017
#           - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
#           - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
#       depends_on:
#           - mongo
#       restart: always
#       ports:
#         - 8081:8081
#       networks:
#         - training
#       labels:
#         - traefik.enable=false

#   nsqlookupd:
#     image: nsqio/nsq
#     ports:
#       - 4160:4160
#       - 4161:4161
#     command: /nsqlookupd
#     networks:
#       - training
#     labels:
#       - traefik.enable=false

# #### IF CONNECTING FROM localhost to nsqd docker container add 127.0.0.1 nsqd to /etc/hosts on the host machine
#   nsqd:
#     image: nsqio/nsq
#     ports:
#       - 4150:4150
#       - 4151:4151
#     links:
#       - nsqlookupd:nsqlookupd
#     command: /nsqd -lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=nsqd
#     networks:
#       - training
#     labels:
#       - traefik.enable=false

#   nsqadmin:
#     image: nsqio/nsq
#     ports:
#       - 4171:4171
#     links:
#       - nsqlookupd:nsqlookupd
#       - nsqd:nsqd
#     command: /nsqadmin -lookupd-http-address=nsqlookupd:4161
#     networks:
#       - training
#     labels:
#       - traefik.enable=false

  training-py:
    image: public.ecr.aws/b8h3z2a1/sravz/training:${SRAVZ_TRAINING_VERSION}
    env_file:
      - .env
    environment:
      - NODE_ENV=local
      - NSQ_HOST=nsqd
      - NSQ_LOOKUPD_HOST=nsqlookupd
      - MONGOLAB_URI=mongodb://sravz:sravz@mongo:27017/sravz
      - MONGOLAB_SRAVZ_HISTORICAL_URI=mongodb://sravz_historical:sravz_historical@mongo:27017/sravz_historical
    command: tail -F anything
    volumes:
      - ~/.aws:/home/ubuntu/.aws:ro
      - ./:/home/ubuntu/workspace
    restart: always
    # depends_on:
    #   - nsqlookupd
    #   - nsqadmin
    #   - nsqd
    #   - mongo
    networks:
      - training
    labels:
      - traefik.enable=false

  training-go:
    image: public.ecr.aws/sravz/sravz/backend-go:v62
    env_file:
      - .env
    environment:
      - NODE_ENV=local
      - NSQ_HOST=nsqd
      - NSQ_LOOKUPD_HOST=nsqlookupd
      - MONGOLAB_URI=mongodb://sravz:sravz@mongo:27017/sravz
      - MONGOLAB_SRAVZ_HISTORICAL_URI=mongodb://sravz_historical:sravz_historical@mongo:27017/sravz_historical
    command: tail -F anything
    volumes:
      - ~/.aws:/home/ubuntu/.aws:ro
      - ./:/workspace
    restart: always
    networks:
      - training
    labels:
      - traefik.enable=false



