  
### Read only operations ###  
- name: get user
  raw: >
    mongo admin  --port {{ mongos_port }} -u admin -p "{{mongo_admin_pass}}" --authenticationDatabase admin --eval "db.getUser(\"{{item}}\")"
  tags:
    - get_user_roles   
  with_items: "{{ user_names }}"       
  when: get_user_roles  
  