---
#This Playbook configures the mongos service of mongodb

- name: Create the mongos configuration file
  become: true
  template: src=mongos.conf.j2 dest=/etc/mongodb/mongos-{{ item.instance_name }}.conf
  with_items: "{{ mongodb_config_items.mongos_instances }}"

- name: create mongos data directory
  become: true
  file: path={{ item.mongodb_datadir_prefix }}/mongos-{{ item.instance_name }} state=directory owner=mongod group=mongod
  with_items: "{{ mongodb_config_items.mongos_instances }}"   


- name: Copy the keyfile for authentication
  become: true
  copy: src=secret dest={{ item.mongodb_datadir_prefix }}/mongos-{{ item.instance_name }}/secret owner=mongod group=mongod mode=0400
  with_items: "{{ mongodb_config_items.mongos_instances }}"

- name: Copy pem file
  become: true
  copy: src=mongodb.pem dest=/etc/mongodb/mongodb.pem owner=mongod group=mongod mode=0400


#- name: Create the mongos startup file
#  template: src=mongos.j2 dest=/etc/init.d/mongos mode=0655

#- name: Create the mongos configuration file
#  template: src=mongos.conf.j2 dest=/etc/mongos.conf

#- name: Copy the keyfile for authentication
#  copy: src=roles/mongod/files/secret dest={{ mongodb_datadir_prefix }}/secret owner=mongod group=mongod mode=0400

#- name: Start the mongos service
#  command: creates=/var/lock/subsys/mongos /etc/init.d/mongos start
#- name: pause
#  pause: seconds=20

#- name: copy the file for shard test
#  template: src=testsharding.j2 dest=/tmp/testsharding.js

#- name: copy the file enable  sharding
#  template: src=enablesharding.j2 dest=/tmp/enablesharding.js

#########################################3


  