---
- name: Check if systemd exists
  stat: path=/etc/systemd/system
  register: systemd_check

- name: Install nsqadmin systemd service
  template:
    src: nsqadmin.service.j2
    dest: /etc/systemd/system/nsqadmin.service
  when: systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart nsqadmin
  become: yes

# For fresh install restart does not work, so start the service
- name: is nsqadmin already running?
  shell: service nsqadmin status warn=false
  register: _svc_nsqadmin
  failed_when: _svc_nsqadmin.rc != 0 and ("unrecognized service" not in _svc_nsqadmin.stderr)
  ignore_errors: true

- name: start nsqadmin if not running
  service: name=nsqadmin state=started
  when: "_svc_nsqadmin.rc != 0"
