---
- name: Update apt
  become: yes
  apt:
    cache_valid_time: 1800
    update_cache: yes
  tags:
    - build
    - apt
    - apt-update

- name: Install JDK
  become: yes
  apt:
    name: ["openjdk-8-jre"]

# Create Kafka group
- name: Create Kafka group
  become: yes
  group:
    name: "{{ kafka.group }}"
    state: present

# Create Kafka user
- name: Create Kafka user
  become: yes
  user:
    name: "{{ kafka.user }}"
    comment: "Kafka user"
    group: "{{ kafka.group }}"

- name: Ensure install folders
  become: yes
  become_user: "{{ kafka.user }}"
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "/home/{{ kafka.user }}/tmp"
    - "/home/{{ kafka.user }}/log"
    - "/home/{{ kafka.user }}/data"

- name: Remove lost+found in the datadir
  become: yes
  file:
    path: "/home/{{ kafka.user }}/data/lost+found"
    state: absent

- name: Fetch kafka binary package
  become: yes
  become_user: "{{ kafka.user }}"
  get_url:
    dest: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"
    url: "{{ kafka.apache_mirror }}/kafka/{{ kafka.version_kafka }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"

- name: Uncompress the kafka tar
  become: yes
  become_user: "{{ kafka.user }}"
  unarchive:
    copy: no
    creates: "/home/{{ kafka.user }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}"
    dest: "/home/{{ kafka.user }}"
    src: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"

- name: Link kafka to the right version
  become: yes
  become_user: "{{ kafka.user }}"
  file:
    path: "/home/{{ kafka.user }}/kafka"
    src: "/home/{{ kafka.user }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}"
    state: link

- name: link config dir
  become: yes
  become_user: "{{ kafka.user }}"
  file:
    force: yes
    path: "/home/{{ kafka.user }}/etc"
    src: "/home/{{ kafka.user }}/kafka/config"
    state: link

- name: Copy Kafka brokers systemd service files
  become: yes
  template:
    src: kafka.systemd.j2
    dest: /etc/systemd/system/kafka_broker_{{item}}@{{item}}.service
    owner: root
    group: root
    mode: 644
  with_sequence: start={{no_broker_start_index}} end={{no_broker_end_index}}
  notify: reload systemd
  tags:
    - copy_kafka_systemd_file

#- name: systemd start script
#  become: yes
#  template:
#    src: kafka.systemd.j2
#    dest: /etc/systemd/system/kafka.service
#    owner: root
#    group: root
#    mode: 644
#  notify: start kafka
#  tags: kafka
