---
# Needed to ensure some services start properly
- name: Set hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
  notify:
    - restart kafka services
  tags:
    - kafka_configure

# Create Kafka server.properties
- name: Create server.properties
  become: yes
  become_user: "{{ kafka.user }}"
  template:
    dest: "/home/{{ kafka.user }}/etc/server{{item}}.properties"
    mode: 0640
    src: server.properties.j2
  with_sequence: start={{no_broker_start_index}} end={{no_broker_end_index}}
  notify:
    - restart kafka services
  tags:
    - copy_server_properties,kafka_configure

- name: Ensure Kafka is running
  become: yes
  service:
    name: "kafka_broker_{{item}}@{{item}}.service"
    enabled: yes
    state: started
  with_sequence: start={{no_broker_start_index}} end={{no_broker_end_index}}

- name: Wait for Kafka port
  wait_for:
    host: "{{kafka_advertised_host_name}}"
    port: "{{ kafka.port }}"
    state: started
    timeout: 30
  tags:
    - copy_server_properties,kafka_configure