# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/ubuntu-18.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # Uses Vagrant host name which is hostonly network and hence all ports are accessible
  # config.vm.network "forwarded_port", guest: 3030, host: 23030, host_ip: '127.0.0.1'
  # config.vm.network "forwarded_port", guest: 5858, host: 25858, host_ip: '127.0.0.1'
  config.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.4"

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "3000"
     vb.cpus = 8
   end

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/home/vagrant/training/", owner: "vagrant", group: "vagrant", mount_options: ["dmode=775,fmode=666"], rsync__exclude: [".git/"], type: "virtualbox", id: "training"

  config.vm.provision "shell", :path => "provision.sh"

end


