---
kafka:
  apache_mirror: http://apache.mirror.anlx.net/
  auto_create_topics: "false"
  conf_dir: /home/kafka/etc
  data_dir: /home/kafka/data
  group: kafka
  heap_opts: "-Xmx{{ (ansible_memtotal_mb / 2) | int }}m -Xms{{ (ansible_memtotal_mb / 2) | int }}m"
  hosts:
    - localhost
  log_cleanup_interval_mins: 1
  log_dir: /home/kafka/log
  log_flush_interval_messages: 10000
  log_flush_interval_ms: 1000
  log_level: WARN
  log_retention_bytes: 104857600  #100 M
  log_retention_hours: 24
  log_segment_bytes: 104857600
  num_io_threads: 2
  num_network_threads: 2
  num_partitions: 2
  port: 9092
  socket_receive_buffer_bytes: 1048576
  socket_request_max_bytes: 104857600
  socket_send_buffer_bytes: 1048576
  systemd_service: /etc/systemd/system/kafka.service
  tarball_location: /home/kafka/tmp
  use_systemd: yes
  user: kafka
  version_kafka: "2.3.0"
  version_scala: "2.12"

  # Zookeeper options
  zookeeper_connection_timeout_ms: 1000000

  # Kakfa options
  kafka_heap_opts: "-Xmx1G -Xms1G"

# Kakfa options
kafka_hosts: "{{ansible_fqdn}}:9092,{{ansible_fqdn}}:9093,{{ansible_fqdn}}:9094"
kafka_data_dir: /home/kafka/data
kafka_version: 0.8.1.1
run_mode: Deploy
skip_install: False
kafka_num_network_threads: 2
kafka_num_io_threads: 2
kafka_num_partitions: 2
kafka_port: 9092
kafka_socket_send_buffer_bytes: 1048576
kafka_socket_receive_buffer_bytes: 1048576
kafka_socket_request_max_bytes: 104857600
kafka_log_flush_interval_messages: 10000
kafka_log_flush_interval_ms: 1000
kafka_log_retention_bytes: 104857600  #100 M
kafka_log_retention_hours: 24
kafka_log_segment_bytes: 104857600
kafka_log_cleanup_interval_mins: 1
kafka_heap_opts: "-Xmx1G -Xms1G"
kafka_conf_dir: /home/kafka/etc
kafka_data_dir: /home/kafka/data
kafka_group: kafka
kafka_user: kafka
kafka_log_dir: /home/kafka/log
kafka_systemd_service: /etc/systemd/system/kafka.service
kafka_auto_create_topics: "false"
monasca_wait_for_period: 30
monasca_log_level: WARN
zookeeper_connection_timeout_ms: 1000000
zookeeper_host_port: 2181
zookeeper_hosts:
  - "{{ansible_fqdn}}"
kafka_home_dir: /home/kafka/kafka/bin/
systemd_service_action: restarted
no_broker_start_index: 1
no_broker_end_index: 3