[package]
name = "sravz"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "server"
path = "src/main.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"

[dependencies]
tokio-nsq = "0.14.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
gethostname = "0.4.3"