# Add Go Root

- name: "Checks if the environment file already has an entry for {{ item.name }}"
  replace:
    dest="{{profile_path}}"
    regexp="export {{ item.name }}=(.*)"
    replace="export {{ item.name }}={{ item.value }}"
  register: checkIfItemIsHere
  tags:
    - add_govars_to_profile
    - update_path_variable

- name: "Add a {{ item.name }} entry with {{ item.name }} if the {{ item.name }} is not already defined"
  lineinfile:
    dest="{{profile_path}}"
    state=present
    line="export {{ item.name }}={{ item.value }}"
    regexp=''
    insertafter=EOF
  when: checkIfItemIsHere == false
  tags:
    - add_govars_to_profile
    - update_path_variable
    
- name: "Add {{ item.name }} to the {{profile_path}}"
  lineinfile:
    dest="{{profile_path}}"
    state=present
    backrefs=no
    regexp="export {{ item.name }}=(.*)"
    line="export {{ item.name }}={{ item.value }}" 
  when: checkIfItemIsHere
  tags:
    - add_govars_to_profile
    - update_path_variable