---
# Create website common task
  - name: Install dotnet4.6.1
    win_chocolatey:
      name: dotnet4.6.1
    tags:
      - install_dotnet      
    when: install_dot_net 

  - name: Sravz API Dev Website physical_path directory
    win_file:
      path: 'c:\sites\{{app_env_name}}'
      state: directory

  - name: App Pool with .NET 4.0
    win_iis_webapppool:
      name: '{{app_env_name}}'
      state: started
      attributes: 
        managedRuntimeVersion: v4.0
        ProcessModel.LoadUserProfile: True
    register: webapppool

  - name: Copy sravz.pfx files
    win_copy:
      src: /mnt/c/workspace/cert/sravz.pfx
      dest: c:\sites\
    tags:
      - copy_sravz_pfx

  - name: Import certificate be used by IIS
    win_certificate_store:
      path: c:\sites\sravz.pfx
      file_type: pkcs12
      password: "{{PFX_PASSWORD}}"
      store_location: LocalMachine
      key_storage: machine
      state: present
    tags:
      - copy_sravz_pfx
  
  - name: Sravz API HTTP Binding
    win_iis_website:
      name: "{{app_env_name}}"
      state: started
      ssl: true
      port: "{{iis_http_port}}"
      ip: "*"
      hostname: "{{iis_host_name}}.sravz.com"
      application_pool: "{{app_env_name}}"
      physical_path: "c:\\sites\\{{app_env_name}}"
      parameters: 'logfile.directory:c:\sites\logs'
    register: website
    when: iis_http_port is defined    
    tags:
      - create_iis_bindings
      - create_iis_http_bindings

  - name: Sravz API HTTPS Binding
    win_iis_webbinding:
      name: "{{app_env_name}}"
      host_header: "{{iis_host_name}}.sravz.com"
      protocol: https
      port: "{{iis_https_port}}"
      certificate_hash: "{{certifcate_hash}}"
      state: present
    when: iis_https_port is defined          
    tags:
      - create_iis_bindings
      - create_iis_https_bindings