---
# handlers file for ansible-nsq

- name: reload daemon
  command: systemctl daemon-reload
  become: yes

- name: restart nsqd
  systemd:
    name: nsqd
    state: restarted
    enabled: yes
  become: yes

- name: restart nsqadmin
  systemd:
    name: nsqadmin
    state: restarted
    enabled: yes
  become: yes

- name: restart nsqlookupd
  systemd:
    name: nsqlookupd
    state: restarted
    enabled: yes
  become: yes
