---
# This playbook  deploys the mongodb configurationdb  servers

- name: Create data directory for mongoc configuration server
  become: true
  file: path={{ item.mongodb_datadir_prefix }}/configdb-{{ item.instance_name }} state=directory owner=mongod group=mongod
  with_items: "{{ mongodb_config_items.mongoc_instances }}"

- name: Copy the keyfile for authentication
  become: true
  copy: src=secret dest={{ item.mongodb_datadir_prefix }}/configdb-{{ item.instance_name }}/secret owner=mongod group=mongod mode=0400
  with_items: "{{ mongodb_config_items.mongoc_instances }}"

- name: Create the mongo configuration server file
  become: true
  template: src=mongoc.conf.j2 dest=/etc/mongodb/mongoc-{{ item.instance_name }}.conf
  with_items: "{{ mongodb_config_items.mongoc_instances }}"

- name: Copy pem file
  become: true
  copy: src=mongodb.pem dest=/etc/mongodb/mongodb.pem owner=mongod group=mongod mode=0400


#- name: pause
#  pause: seconds=20

#- name: add the admin user
#  mongodb_user: database=admin name=admin password={{ mongo_admin_pass }} login_port={{ mongoc_port }} state=present
#  ignore_errors: yes
#  tags:
#    - add_admin_user
