#- name: Set directory ownership
#  become: true
#  file: dest={{item}} owner=mongod group=mongod state=directory recurse=yes
#  with_items:
#  - /var/log/mongodb
#  - /var/run/mongo
#  - /etc/mongodb/
#  when: create_mongod_service_directories

### Perform action on the services
- name: Perform acton on mongod. Wait to transition to primary
  become: true
  service:
    name: mongod@{{item.instance_name}}.service
    state: '{{systemd_service_action}}'
    enabled: true
  with_items: '{{ mongodb_config_items.instances }}'
  when: touch_mongod_service

- name: Pause for any pending replication
  pause:
    minutes: '{{pause_for_minutes_after_finishing}}'
  when: touch_mongod_service

- name: Perform acton on mongoc. Wait to transition to primary
  become: true
  service:
    name: mongoc@{{item.instance_name}}.service
    state: '{{systemd_service_action}}'
    enabled: true
  with_items: '{{ mongodb_config_items.mongoc_instances }}'
  when: touch_mongoc_service
- name: Pause for any pending replication
  pause:
    minutes: '{{pause_for_minutes_after_finishing}}'
  when: touch_mongoc_service

- name: Perform acton on mongos. Wait to transition to primary
  become: true
  service:
    name: mongos@{{item.instance_name}}.service
    state: '{{systemd_service_action}}'
    enabled: true
  with_items: '{{ mongodb_config_items.mongos_instances }}'
  when: touch_mongos_service

- name: Pause for any pending replication
  pause:
    minutes: '{{pause_for_minutes_after_finishing}}'
  when: touch_mongos_service

