---
- name: Check if systemd exists
  stat: path=/etc/systemd/system
  register: systemd_check

- name: Install nsqd systemd service
  template:
    src: nsqd.service.j2
    dest: /etc/systemd/system/nsqd.service
  when: systemd_check.stat.exists == true
  notify:
    - reload daemon
    - restart nsqd
  become: yes

# For fresh install restart does not work, so start the service
- name: is nsqd already running?
  shell: service nsqd status warn=false
  register: _svc_nsqd
  failed_when: _svc_nsqd.rc != 0 and ("unrecognized service" not in _svc_nsqd.stderr)
  ignore_errors: true

- name: start nsqd if not running
  service: name=nsqd state=started
  when: "_svc_nsqd.rc != 0"
