---
- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest="/tmp/repset_init.{{ item.name }}.js"
  with_items: "{{ mongodb_config_items.replica_sets }}"
  when: touch_mongod_service  
    
- name: Initialize the replication set
  shell: /usr/bin/mongo --port {{ item.primary.mongod_port }} "/tmp/repset_init.{{ item.name }}.js"
  with_items: "{{ mongodb_config_items.replica_sets }}"
  when: touch_mongod_service  
  
- name: Create the file to initialize the mongod replica set
  template: src=repset_init.j2 dest="/tmp/repset_init.{{ item.name }}.js"
  with_items: "{{ mongodb_config_items.mongoc_replica_sets }}"
  when: touch_mongoc_service  
    
- name: Initialize the replication set
  shell: /usr/bin/mongo --port {{ item.primary.mongod_port }} "/tmp/repset_init.{{ item.name }}.js"
  with_items: "{{ mongodb_config_items.mongoc_replica_sets }}"
  when: touch_mongoc_service  