---
### Write operations ###
#### Should be the first task
- name: Pause for any pending replication
  pause:
    minutes: "{{pause_for_minutes_before_starting}}"
  when: not shards_readonly 

- name: Add shards
  raw: >
    mongo admin  --port {{ item.mongos_port }} -u admin -p "{{mongo_admin_pass}}" --authenticationDatabase admin --eval "sh.addShard(\"{{item.name}}/{{item.primary_host_port}}\")"
  tags:
    - add_mongodb_shards
  with_items: "{{ mongodb_config_items.mongos_shards }}"       
  when: add_mongodb_shards  
  
- name: Enable sharding on a database
  raw: >
    mongo {{ item.database }}  --port {{ mongos_port }} -u {{ item.user}} -p "{{ item.password}}" --authenticationDatabase admin --eval "sh.enableSharding(\"{{ item.database}}\")"
  tags:
    - enable_mongodb_db_sharding
  with_items: "{{ mongodb_dbs_to_enable_sharding }}"       
  when: enable_mongodb_db_sharding  

#### Should be the last task
- name: Pause for any pending replication
  pause:
    minutes: "{{pause_for_minutes_after_finishing}}"  
  when: not shards_readonly

  
### Read only operations ###  
- name: get shards
  raw: >
    mongo admin  --port {{ mongos_port }} -u admin -p "{{mongo_admin_pass}}" --authenticationDatabase admin --eval "sh.status()"
  tags:
    - get_shard_status   
  when: get_shard_status  
    